release:
  branching:
    execution:
      time: "19:00:00"
    schedule:
      - on: "2023-05-30"
        name: release/0.39
        initial-tag:
          create: false
          name: v0.39.0-alpha.2

