name: "Validate Gradle Wrapper"
  push:
    branches: [ elasticsearch ]
on: [push]

permissions:
  contents: read

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
