name: Release Drafter

on:
  push:
    branches: [ cryostat ]





jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
